name: LuaPluginLib CI/CD Release process

on: [push, pull_request, workflow_dispatch]

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    if:
      contains('
        refs/heads/beta
        refs/heads/alpha
        refs/heads/main
      ', github.ref)
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Pack
      uses: edwardspec/github-action-pack-starbound-mod@v1
      with:
        outputFilename: LPL_NonLethalFallDamage.pak
    - name: Install release dependencies
      run: npm ci
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npx semantic-release
